import React from 'react';
import { X, Sparkles, Shield, Cpu, CheckCircle2, ArrowRight } from 'lucide-react';

interface AIAssistantModalProps {
  isOpen: boolean;
  onClose: () => void;
  isLoading: boolean;
  critiqueText: string;
  error?: string | null;
}

export const AIAssistantModal: React.FC<AIAssistantModalProps> = ({
  isOpen,
  onClose,
  isLoading,
  critiqueText,
  error,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-700/80 rounded-2xl w-full max-w-3xl overflow-hidden shadow-2xl flex flex-col max-h-[85vh]">
        {/* Modal Header */}
        <div className="px-5 py-4 border-b border-slate-800 bg-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-600 to-purple-600 flex items-center justify-center text-white shadow-md shadow-indigo-600/30">
              <Sparkles className="w-4 h-4 text-yellow-300" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white font-mono flex items-center gap-2">
                SchemaGuardian AI Principal Architect Review
                <span className="text-[10px] font-sans px-2 py-0.5 rounded-full bg-indigo-950 text-indigo-300 border border-indigo-800 font-semibold">
                  Autonomous Advisory
                </span>
              </h3>
              <p className="text-xs text-slate-400">
                Evaluation of Normal Form Boundaries, Concurrency Ingestion & HIPAA/GDPR Compliance
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-4 text-xs font-sans text-slate-200 leading-relaxed">
          {isLoading ? (
            <div className="py-16 flex flex-col items-center justify-center space-y-3">
              <div className="w-10 h-10 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
              <div className="text-sm font-mono text-cyan-300 font-bold">
                Synthesizing Autonomous Architectural Review...
              </div>
              <p className="text-xs text-slate-500 max-w-sm text-center">
                Evaluating BCNF anomalies, cursor locking constraints, and cryptographic masking rules...
              </p>
            </div>
          ) : error ? (
            <div className="bg-rose-950/40 border border-rose-800/80 rounded-xl p-4 text-rose-300 space-y-2">
              <div className="font-bold font-mono">Architect Review Status</div>
              <p>{error}</p>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="bg-slate-950/80 border border-slate-800/80 rounded-xl p-4 text-xs font-mono text-slate-300 leading-relaxed whitespace-pre-wrap selection:bg-cyan-500/30">
                {critiqueText}
              </div>

              <div className="bg-indigo-950/30 border border-indigo-800/40 rounded-xl p-3.5 flex items-start gap-2.5">
                <Shield className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
                <div className="text-[11px] text-slate-300 leading-relaxed">
                  <strong className="text-white">Continuous Compliance Assurance:</strong> All forward and rollback DDL generated by SchemaGuardian AI are idempotent (`IF NOT EXISTS`) and wrap batch migrations within transaction controls to prevent lock starvation.
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-5 py-3 border-t border-slate-800 bg-slate-950 flex items-center justify-between">
          <span className="text-[11px] font-mono text-slate-500">
            Powered by Gemini 3.8 Flash Autonomous Engine
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono font-medium transition-colors cursor-pointer"
          >
            Close Advisory
          </button>
        </div>
      </div>
    </div>
  );
};
